# Generated by Django 3.2.15 on 2022-10-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='desc',
            field=models.TextField(default='movie description!!'),
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='/images/default.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='movie title', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default='2022'),
        ),
    ]
