# Generated by Django 3.2.15 on 2022-10-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_auto_20221001_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
