# Generated by Django 3.2.15 on 2022-10-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_alter_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='https://images.app.goo.gl/PcMcoWcL5Jzx971s5', upload_to='images'),
        ),
    ]
