# Generated by Django 3.2.15 on 2022-10-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_alter_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='https://whetstonefire.org/wp-content/uploads/2020/06/image-not-available.jpg', upload_to='images'),
        ),
    ]
